[project]
name = "agentic-rag-frontend"
version = "0.1.0"
description = "Streamlit frontend for Agentic RAG"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.0",
    "requests>=2.0",
]